### ISSUE TITLE
Make echemdb pip installable and publish on conda-forge

### ISSUE THREAD

**Issue by DunklesArchipel** [echemdb/echemdb#10]
Initially, we want to publish the echemdb package on PyPI and conda-forge.

- [x] PyPI
- [x] conda-forge

**Comment by saraedum** [comment]
Before we do this, should we rename this project to `echemdb`? That name would then be quite overloaded being

* the actual database, living in this repository
* the website visualizing the database
* the Python package to interact with the database and create the website

I don't think it's terribly confusing that these three things are all called the same.

**Comment by DunklesArchipel** [comment]
I fully agree with renaming the repo to `echemdb`. The website can be moved elsewhere later.
