### ISSUE TITLE
package won't work with python 3.9

### ISSUE THREAD

**Issue by Zausinator** [echemdb/echemdb#36]
The package does not work with python versions 3.8.3 and lower, due to the functools requiring the cache property.
When I updated to python 3.10.4 it worked. From what I can see the cache property was introduced for python version 3.9.0 so maybe we should add
```
{"python_requires": ">=3.9.0",...}
```
to the ```setup.py```

**Comment by DunklesArchipel** [comment]
Thank you for the hint!

**Comment by saraedum** [comment]
We don't even have such a constraint in the svgdigitizer. (I think we just added it to the CI workflow when we noticed that we need 3.9)

**Comment by DunklesArchipel** [comment]
The bug should be fixed in V 0.2.0.
