### ISSUE TITLE
Citation

### ISSUE THREAD

**Issue by Zausinator** [echemdb/echemdb#56]
Hi!
I would like to use the echemdb for a current project, is there a citation available?
Thanks!

**Comment by DunklesArchipel** [comment]
You can use zenodo to cite our project: https://zenodo.org/record/6502901

We are migrating to [unitpackage](https://github.com/DunklesArchipel/unitpackage), which will receive a new DOI. The project will be identical to this one, except that it has a more generic name.

**Comment by Zausinator** [comment]
Sweet, thanks! :)
